dropout: 0.45
emb_dropout: 0.25
embedding_size: 256
emphasize_eeg: false
feedback: false
hidden_units: 192
input_vocab_size: 7
kernel_size: 3
levels: 7
output_vocab_size: 3764
seq_length: 192
tied_weights: false
