dropout: 0.45
emb_dropout: 0.25
embedding_size: 256
emphasize_eeg: false
feedback: false
hidden_units: 64
input_vocab_size: 22372
kernel_size: 3
levels: 5
output_vocab_size: 22372
seq_length: 64
tied_weights: false
