dropout: 0.45
emb_dropout: 0.25
embedding_size: 512
emphasize_eeg: false
feedback: true
hidden_units: 128
input_vocab_size: 17324
kernel_size: 3
levels: 6
output_vocab_size: 16447
seq_length: 64
tied_weights: false
